### ISSUE TITLE
fix: container proxy with 404 on static resources

### ISSUE THREAD

**Issue by ntorga** [goinfinite/ez-issue-tracker#137]
When we proxy the /containerId/ url, the OS front is trying to load the static files (.js and .css) from /_/ instead of /containerId/.

Using nginx sub_module would work but the best workaround. Maybe we should ditch /_/ for good.

**Comment by ntorga** [comment]
@polillomm About this issue, it's actually regarding os-dash rather than Control itself. We need to make sure the os-dash loads its assets from the base of the page, which may be `/`, or `/_/` or even `/containerId/_/` for instance. Do you have any thoughts on that?

As I explained, I could use nginx sub_module to rewrite the HTML but since we do have control over the HTML, we might be able to fix this on Quasar side so the css/js files are loaded with a dynamic base URL.

By the way, ditching the `/_/` is a good idea but we would also need to move to another place as / would be reserved for the new HTMX+Alpine.js version. Maybe keep `/_/` so we use it for Quasar/Vue while the new pages created directly on the backend via HTMX+Alpine.js uses `/`.

**Comment by polillomm** [comment]
@ntorga Perhaps this is a very simplistic solution, but couldn't we create a default mapping to serve these assets during the migration? This mapping could be removed once the migration to **HTMX** + **Alpine.js** version is complete. I'm not sure if this is feasible, but it might be easier than using _sub_module_.

As soon as we finish everything necessary, we can move the assets directly to `/`, avoiding any further changes to what we already have ready in **Quasar**.

**Comment by ntorga** [comment]
We discussed internally and was decided to keep `/_/` prefix so we can use it for Vue pages. Once we start having HTMX pages, we'll be using the root path `/`.

For the issue at hand, @polillomm will fix on the Quasar/Vue side so the assets are loaded based on the root page, which may be either `/_/` when SpeediaOS is loaded directly or via `/containerId/_/` when the container proxy from Control is used.

**Comment by ntorga** [comment]
Heads up: the planned wasn't possible on the frontend side. Will do via NGINX later.

**Comment by ntorga** [comment]
Heads up: NGINX was able to replace some of the URLs, but @polillomm will have to fix OS dash to send the API endpoints via the components instead of relying solely on the request service. I'll be taking a vacation for the next weeks, but soon as I come back I intent to have this fully functional (for good).

One idea: add a second prop to the request services (all of them) requesting the baseUri for the api call since only the components seems to be able to retrieve the correct baseUri.

**Comment by ntorga** [comment]
This task will be archived because we're refactoring the OS dashboard entirely to HTMX and this won't be an issue anymore.
